version: '3.9'
name: 'vrenda'

services:
  api:
    container_name: api
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./vrenda_api:/vrenda_api
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env